### ISSUE TITLE
ERROR: web3 is not defined so, smart contract is not responding 

### ISSUE THREAD

**Issue by Meharab** [ThisIsCodeXpert/Ethereum-DApp-Best-Beginner-Tutorials-2020#1]
i have node.js and metamask in my system(windows 10)
i cloned you project from github and runned it by following command
1. npm install
2. node index.js
the  UI deployed perfectly in localhost:3000 but when i try to vote the transaction is not working!!!
then i saw content on smart contract is not rendering!!!
then i checked metamask , which was connected and have 1 ether on ropsten network!!!
then i try ganache (local blockchain provider) and still the transaction is not working!!!
then i download brave browser but it did not solve the problem!!!
then i paste the smart contract in remix and get the ABI and smart contract address and still not working!!!
then i goto developer tool of browser and saw below error!!!!...i have no idea of this error!!!!...how can i solve this???
![Screenshot 2021-01-28 121755](https://user-images.githubusercontent.com/33731973/106098971-262c6680-6164-11eb-8bf0-302db4c186d5.png)

**Comment by Meharab** [comment]
the error is saying web3 is not defined but ...??? (hereis the script)

`<script>
        var myContract;
        async function CheckMetamaskConnection() {
            // Modern dapp browsers...
            if (window.ethereum) {
                window.web3 = new Web3(window.ethereum);
                try {
                    // Request account access if needed
                    await ethereum.enable();
                    // Accounts now exposed
                    return true;
                } catch (error) {
                    // User denied account access...
                    return false;
                }
            }
            // Legacy dapp browsers...
            else if (window.web3) {
                window.web3 = new Web3(web3.currentProvider);
                // Accounts always exposed

                return true;
            }
            // Non-dapp browsers...
            else {
                console.log('Non-Ethereum browser detected. You should consider trying MetaMask!');
                return false;
            }
        }

        $(document).ready(async function () {
            var IsMetamask = await CheckMetamaskConnection();
            if (IsMetamask) {
                myContract = await web3.eth.contract(SmartContractABI).at(SmartContractAddress);
                getCandidate(1);
                getCandidate(2);

                await myContract.eventVote({
                    fromBlock:0
                }, function(err, event){
                    console.log("event :", event);
                    getCandidate(event.args._candidateid.toNumber());
                });
                console.log("myContract :", myContract);
                console.log("Metamask detected!")
            } else {
                console.log("Metamask not detected");
                Swal.fire({
				  icon: 'error',
				  title: 'Oops...',
				  text: 'Metamask not detected!',
				  onClose() {
				  	location.reload();
				  }
				});
            }
        });

        async function getCandidate(cad){
            await myContract.candidates(cad, function(err, result){
                if (!err) {
                    console.log("result : ", result);
                    document.getElementById("cad" + cad).innerHTML = result[1];
                    document.getElementById("cad"+cad+'count').innerHTML = result[2].toNumber();
                }
            });
        }

        async function Vote(cad){
            await myContract.vote(cad, function(err, result){
                if(!err){
                    console.log("We are winning!");
                } else{
                    console.log("Can not connect to the smart contract");
                }
            })
        }

    </script>`

**Comment by Meharab** [comment]
solve it! the problem was on remix

**Comment by noorchauhan** [comment]
I am facing a similar issue, please can you specify what needs to be done?
